//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uNeed.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderView
    {
        public int OrderID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public Nullable<double> Paid { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public int ShipperID { get; set; }
        public int PaymentID { get; set; }
        public int CustomerID { get; set; }
        public int OrderDetailID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int ProductID { get; set; }
    }
}
