//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uNeed.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailView
    {
        public int OrderID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Paid { get; set; }
        public string PaymentType { get; set; }
        public string ProductName { get; set; }
        public string Picture { get; set; }
        public string CompanyName { get; set; }
    }
}
